"""
全局配置包
"""

from .settings import (
    API_BASE_URL, INTERNAL_TOKEN, DATA_DIR, LOG_LEVEL,
    TRADE_START_HOUR, TRADE_START_MINUTE, TRADE_END_HOUR, TRADE_END_MINUTE,
    REQUEST_DELAY_MIN, REQUEST_DELAY_MAX,
    MAX_FAIL_COUNT, FAIL_SLEEP_TIME,
    EARLY_MORNING_INTERVAL,
    USE_PROXY, PROXY_POOL_API, PROXY_VALIDATE_URL,
    PROXY_MIN_AVAILABLE, PROXY_FETCH_COUNT,
    CONSECUTIVE_EMPTY_THRESHOLD, SLEEP_EXTRA_SECONDS,
)

from .change_types import (
    CHANGE_TYPES, LEVEL_MAPPING, CYCLE_MAPPING,
    SHORT_TERM_TYPES, MID_TERM_TYPES, LONG_TERM_TYPES,
)

__all__ = [
    'API_BASE_URL', 'INTERNAL_TOKEN', 'DATA_DIR', 'LOG_LEVEL',
    'TRADE_START_HOUR', 'TRADE_START_MINUTE', 'TRADE_END_HOUR', 'TRADE_END_MINUTE',
    'REQUEST_DELAY_MIN', 'REQUEST_DELAY_MAX',
    'MAX_FAIL_COUNT', 'FAIL_SLEEP_TIME',
    'EARLY_MORNING_INTERVAL',
    'USE_PROXY', 'PROXY_POOL_API', 'PROXY_VALIDATE_URL',
    'PROXY_MIN_AVAILABLE', 'PROXY_FETCH_COUNT',
    'CONSECUTIVE_EMPTY_THRESHOLD', 'SLEEP_EXTRA_SECONDS',
    'CHANGE_TYPES', 'LEVEL_MAPPING', 'CYCLE_MAPPING',
    'SHORT_TERM_TYPES', 'MID_TERM_TYPES', 'LONG_TERM_TYPES',
]
